In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('parkinson_disease.csv')

In [3]:
df

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
0,0,1,0.85247,0.71826,0.57227,240,239,0.008064,0.000087,0.00218,...,1.5620,2.6445,3.8686,4.2105,5.1221,4.4625,2.6202,3.0004,18.9405,1
1,0,1,0.76686,0.69481,0.53966,234,233,0.008258,0.000073,0.00195,...,1.5589,3.6107,23.5155,14.1962,11.0261,9.5082,6.5245,6.3431,45.1780,1
2,0,1,0.85083,0.67604,0.58982,232,231,0.008340,0.000060,0.00176,...,1.5643,2.3308,9.4959,10.7458,11.0177,4.8066,2.9199,3.1495,4.7666,1
3,1,0,0.41121,0.79672,0.59257,178,177,0.010858,0.000183,0.00419,...,3.7805,3.5664,5.2558,14.0403,4.2235,4.6857,4.8460,6.2650,4.0603,1
4,1,0,0.32790,0.79782,0.53028,236,235,0.008162,0.002669,0.00535,...,6.1727,5.8416,6.0805,5.7621,7.7817,11.6891,8.2103,5.0559,6.1164,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,250,0,0.80903,0.56355,0.28385,417,416,0.004627,0.000052,0.00064,...,3.0706,3.0190,3.1212,2.4921,3.5844,3.5400,3.3805,3.2003,6.8671,0
752,250,0,0.16084,0.56499,0.59194,415,413,0.004550,0.000220,0.00143,...,1.9704,1.7451,1.8277,2.4976,5.2981,4.2616,6.3042,10.9058,28.4170,0
753,251,0,0.88389,0.72335,0.46815,381,380,0.005069,0.000103,0.00076,...,51.5607,44.4641,26.1586,6.3076,2.8601,2.5361,3.5377,3.3545,5.0424,0
754,251,0,0.83782,0.74890,0.49823,340,339,0.005679,0.000055,0.00092,...,19.1607,12.8312,8.9434,2.2044,1.9496,1.9664,2.6801,2.8332,3.7131,0
755,251,0,0.81304,0.76471,0.46374,340,339,0.005676,0.000037,0.00078,...,62.9927,21.8152,9.2457,4.8555,3.0551,3.0415,4.0116,2.6217,3.1527,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Columns: 755 entries, id to class
dtypes: float64(749), int64(6)
memory usage: 4.4 MB

In [5]:
df.describe()

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
count,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,...,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000
mean,125.500000,0.515873,0.746284,0.700414,0.489058,323.972222,322.678571,0.006360,0.000383,0.002324,...,26.237251,22.840337,18.587888,13.872018,12.218953,12.375335,14.799230,14.751559,31.481110,0.746032
std,72.793721,0.500079,0.169294,0.069718,0.137442,99.219059,99.402499,0.001826,0.000728,0.002628,...,42.220693,32.626464,25.537464,20.046029,17.783642,16.341665,15.722502,14.432979,34.230991,0.435568
min,0.000000,0.000000,0.041551,0.543500,0.154300,2.000000,1.000000,0.002107,0.000011,0.000210,...,1.509800,1.531700,1.582900,1.747200,1.789500,1.628700,1.861700,1.955900,2.364000,0.000000
25%,62.750000,0.000000,0.762833,0.647053,0.386537,251.000000,250.000000,0.005003,0.000049,0.000970,...,2.408675,3.452800,3.354825,3.077450,2.937025,3.114375,3.665925,3.741275,3.948750,0.000000
50%,125.500000,1.000000,0.809655,0.700525,0.484355,317.000000,316.000000,0.006048,0.000077,0.001495,...,5.586300,7.062750,6.077400,4.770850,4.300450,4.741450,6.725700,7.334250,10.637250,1.000000
75%,188.250000,1.000000,0.834315,0.754985,0.586515,384.250000,383.250000,0.007528,0.000171,0.002520,...,28.958075,29.830850,21.944050,13.188000,10.876150,12.201325,21.922050,22.495175,61.125325,1.000000
max,251.000000,1.000000,0.907660,0.852640,0.871230,907.000000,905.000000,0.012966,0.003483,0.027750,...,239.788800,203.311300,121.542900,102.207000,85.571700,73.532200,62.007300,57.544300,156.423700,1.000000

In [6]:
df.isnull().sum()

id                           0
gender                       0
PPE                          0
DFA                          0
RPDE                         0
                            ..
tqwt_kurtosisValue_dec_33    0
tqwt_kurtosisValue_dec_34    0
tqwt_kurtosisValue_dec_35    0
tqwt_kurtosisValue_dec_36    0
class                        0
Length: 755, dtype: int64

Since there is no null value in dataset we will mode forward for further steps.
since the dataset contains too many features we will remove highly correlated feature except for target feature.

In [4]:
columns = list(df.columns)
for col in columns:
    if col == 'class':
        continue
    filtered_columns = [col]
    for col1 in df.columns:
        if((col == col1) | (col == 'class')):
            continue
        val = df[col].corr(df[col1])
        if val > 0.7:
            columns.remove(col1)
            continue
        else:
            filtered_columns.append(col1)
            
    df = df[filtered_columns]
df.shape

(756, 314)

In [ ]:
#still dataset has lot of feature so we will use only few most important feature
#using chi square test
from sklearn.preprocessing import  MinMaxScaler
from sklearn.feature_selection import SelectKBest, chi2
x = df.drop('class', axis=1)
x_norm = MinMaxScaler().fit_transform(x)
selector = SelectKBest(chi2, k=10)
selector.fit(x_norm, df['class'])
filtered_columns = selector.get_support()
filtered_data = x.loc[:, filtered_columns]
filtered_data['class'] = df['class']
df = filtered_data
df.shape

C:\Users\Gaura\AppData\Local\Temp\ipykernel_532\1884685770.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['class'] = df['class']

(756, 11)

In [19]:
df

,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_26,tqwt_kurtosisValue_dec_25,tqwt_entropy_shannon_dec_15,tqwt_entropy_shannon_dec_11,tqwt_energy_dec_27,tqwt_energy_dec_14,tqwt_energy_dec_12,tqwt_energy_dec_11,gender,class
0,1.5620,1.6058,2.0062,174.6920,4.8840,0.108070,0.012066,0.000239,0.000415,1,1
1,1.5589,1.5772,2.0470,140.8136,4.8483,0.098360,0.010578,0.000297,0.000515,1,1
2,1.5643,1.5921,3.2597,84.8129,1.9849,0.106910,0.012972,0.000248,0.000414,1,1
3,3.7805,1.8829,1.9120,572.9586,3.2053,0.002072,0.021586,0.000703,0.000067,0,1
4,6.1727,1.8821,1.7577,647.2537,2.7170,0.001152,0.023381,0.000648,0.000051,0,1
...,...,...,...,...,...,...,...,...,...,...,...
751,3.0706,10.1906,1.7601,1899.1355,154.3248,0.000012,0.168400,0.022872,0.002938,0,0
752,1.9704,22.4043,3.3455,1648.3375,92.2915,0.000093,0.178860,0.023427,0.002473,0,0
753,51.5607,2.3279,1.6380,327.5390,166.6840,0.000116,0.022846,0.031182,0.009413,0,0
754,19.1607,1.6052,1.5692,361.1472,94.8016,0.000965,0.012893,0.012725,0.003496,0,0
755,62.9927,1.6820,1.7050,249.3561,82.3081,0.000950,0.008702,0.009967,0.002892,0,0

In [6]:
x_count = df['class'].value_counts()
# plt.pie(x.values,
#         labels = x.index,
#         autopct='%1.1f%%')
# plt.show()
x_count

class
1    564
0    192
Name: count, dtype: int64

The dataset is imbalnce so we will use SMOTE for balancing the dataset.

In [7]:
from sklearn.model_selection import train_test_split
x=df.drop('class',axis=1)
y=df['class']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)
x_train.shape,x_test.shape

((604, 10), (152, 10))

In [11]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
x, y = smote.fit_resample(x_train, y_train)
x.shape,y.shape

((892, 10), (892,))

Model Training

In [12]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

models = {
    "Random Forest": RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=200, random_state=42),
    "SVM": SVC(kernel='rbf', probability=True),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Logistic Regression": LogisticRegression(max_iter=500)
}

cv_results = {}

for name, model in models.items():
    scores = cross_val_score(model, x, y, cv=5, scoring='accuracy')
    cv_results[name] = np.mean(scores)
    print(f"{name}: {np.mean(scores):.4f}")

best_model_name = max(cv_results, key=cv_results.get)
best_model = models[best_model_name]
best_model.fit(x, y) 

import pickle
pickle.dump(best_model, open("best_model.pkl", "wb"))
print(f"Best model is {best_model_name} with accuracy {cv_results[best_model_name]:.4f}")

Random Forest: 0.8891
Gradient Boosting: 0.8599
SVM: 0.7208
KNN: 0.7724
Logistic Regression: 0.7522
Best model is Random Forest with accuracy 0.8891